### PR TITLE
This commit fixes #97

### LINKED ISSUE #97: Touch inputs only control first thumb (critical)
This bug prevents use of multi-thumb inputs on mobile.
When the input is a touch event, only the first thumb is consistently controllable. Tapping on the second (rightmost) thumb still controls the first thumb.
Tested on: Android Firefox, Android Chrome, Android Opera, Android Vivaldi
Sandbox: https://mvdm0.csb.app

### PR DESCRIPTION
**Pull request by totalolage**
I don't even understand why it was set the way it was.

### CODE REVIEW

**Comment by felix-kaestner** [comment]
I think this Issue was introduced by #95 . The reason why it was set this way, was to fix #37, which basically means that you can now click in between thumbs and move the closest thumb to the position where you clicked. But I'm not sure why this breaks on mobile while it works perfectly fine on desktop. If you do the same change you did on line 233 you can see that it breaks this behaviour on desktop, since it will always use the first thumb where it should use the closest thumb.

**Comment by totalolage** [comment]
The reason it breaks on mobile is because most (if not all, I can't find that info) modern browsers fire `mouse` events alongside `touch` events (touch events coming first as per the [spec](https://www.w3.org/TR/touch-events/#mouse-events)).
Ideally the `touch` events wouldn't even be registered if it was somehow detected that the browser fires `mouse` on `touch` as this needlessly doubles the number of events handled. But I don't see any elegant way to do that.

**Comment by felix-kaestner** [comment]
That is interesting. But like the spec also suggests 
> If the preventDefault method of touchstart or touchmove is called, the user agent should not dispatch any mouse event that would be a consequential result of the the prevented touch event.

So if it seems to be the issue here that both mouse and touch events are fired then a `e.preventDefault()` in the `onMouseOrTouchStart` method on line 272 should fix the issue.?

Even if both mouse and touch events  are fired, I don't see why this would break  it. Both functions simply calculate the index of the closest thumb. So I think it is more likely to be a problem with how the closest thumb is calculated.

**Comment by felix-kaestner** [comment]
Oh. I'm sorry. I misread the code changes. Your suggested change is absolutely correct! It should be jus `draggedThumbIndex` and **not** `draggedThumbIndex: 0`. You are right. That seems to be my mistake in #95

**Pull request merged**
