### PR TITLE
fix(rtl): correctly picking up new values

### PR DESCRIPTION
**Pull request by gergelyke**
Fixes https://github.com/uber/baseweb/issues/2180

### CODE REVIEW

**Comment by chasestarr** [comment]
do you mind sharing a bit on why this fixes the issue? seems like the vrt looks exactly the same. could we create a previously failing test?

**Comment by gergelyke** [comment]
> do you mind sharing a bit on why this fixes the issue? seems like the vrt looks exactly the same. could we create a previously failing test?

sure, let me update the PR

**Comment by gergelyke** [comment]
@chasestarr - not sure if this better clarifies the issue, please let me know if you'd like to see more of a reproduction

in the base web context, you can see a repro here: https://github.com/uber/baseweb/issues/2180

**Comment by tajo** [comment]
```
info New version: 1.4.3
```

**Pull request merged**
