### PR TITLE
empty value support

### PR DESCRIPTION
**Pull request by ShiiRochi**
This PR contains the implementation of empty value support. 

It allows to pass empty `values` array and touch or click on slider, thus it will create thumb (+ ref for it) and the first value in `values` array.

After the creation of the first value in `values` array, it will not create new thumbs and values on click/touch events.

Also, I created a storybook for that case called 'EmptyValue'.

### CODE REVIEW

**Comment by tajo** [comment]
What is the use-case for this?

**Comment by ShiiRochi** [comment]
For example, for ratings) Imagine that a user has to rate something from 1 to 5 or less/more. Until user has made a choice, showing that rate is zero or something in the middle is not correct [my POV] as soon as it is not a choice made by a user.

Also, there always will be situations when you have no value to pass inside, thus each developer would have a hard mind work on what value to display as default.

**Comment by tajo** [comment]
It seems a bit strange to ever display a slider component without thumbs. How could user even tell it's a slider component then and they are supposed to click on it? 

Are there any example this on the web?

**Comment by ShiiRochi** [comment]
it is available as feature in [react-component/slider](https://github.com/react-component/slider) package. You may see it in storybook of that package in 'slider' section. 

And about empty values themselves and their practical usage, I've used'em on a project I'am working on currently.

About user: user can be told in variety of ways that some component is intractable and he/she can tap/click on it and do something with it. Also you can draw markers with labels.

**Comment by tajo** [comment]
I appreciate the effort but I don't think this feature is worth the additional code and ambiguity.

**Pull request closed without merging**
